name: CodSpeed Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
  # Allows CodSpeed to trigger backtest performance analysis
  # in order to generate initial baseline data.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # required for OIDC authentication with CodSpeed

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setup Rust toolchain, cache and cargo-codspeed
        uses: moonrepo/setup-rust@v1.3.0
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed

      - name: Build benchmark targets
        run: cargo codspeed build

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v6.0.2
        with:
          run: cargo codspeed run
