name: CodSpeed Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
  # Allows CodSpeed to trigger backtest performance analysis
  # in order to generate initial baseline data.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # required for OIDC authentication with CodSpeed

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: Swatinem/rust-cache@v2.9.1

      - name: Install cargo-codspeed
        uses: taiki-e/install-action@v2.70.1
        with:
          tool: cargo-codspeed

      - name: Build benchmark targets
        run: cargo codspeed build

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4.15.0
        with:
          mode: simulation
          run: cargo codspeed run
